import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/lib/contexts/AppContext";
import { CartProvider } from "@/lib/contexts/cartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <AppProvider>
        <CartProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/bg.svg')] bg-zinc-900 bg-no-repeat bg-center bg-cover text-white`}
      >
        {children}
      </body>
      </CartProvider>
      </AppProvider>
    </html>
  );
}
